---
title: "PEC5 Otoño 2025"
author: "UOC"
date: ''
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
fontsize: 12pt
urlcolor: blue
---

**En esta actividad no está permitido el uso de herramientas de inteligencia artificial.
En el plan docente y en la [web sobre integridad académica y plagio de la UOC](https://campus.uoc.edu/estudiant/microsites/plagi/ca/index.html) encontraréis información sobre qué se considera conducta irregular en la evaluación y las consecuencias que puede tener.**

Esta PEC se basará en los datos de las ventas de videojuegos en todo el mundo para títulos lanzados entre 1971 y 2024 (los datos se han obtenido de la web *Maven Analytics* que proporciona un "Data Playground"). Hay incluida información como la puntuación de la crítica, el género, la consola y más.

La base de datos contiene:

1. *title* = variable cualitativa que indica el título del juego
2. *console* = variable cualitativa que indica la consola para la cual se lanzó el juego
3. *genre* = variable cualitativa que indica el género del juego
4. *critic_score*  = puntuación de Metacritic (sobre 10)
5. *total_sales* = ventas globales de copias en millones

Para importar los datos podéis usar las siguientes instrucciones:

```{r}
datos <- read.csv("DATA.csv", header = TRUE, encoding = "UTF-8",
                  stringsAsFactors = TRUE)
datos <- datos[, -1]
```

Os puede ser útil consultar el siguiente material del Reto 4:

1. Módulos: Contraste de hipótesis y Contraste de dos muestras.
1. Actividades Resueltas del Reto 4 (Contraste de hipótesis y Contraste de dos muestras).
1. Procurad usar las funciones propias de R para hacer los cálculos a no ser que se indique lo contrario.

Hay que entregar la práctica en formato ".pdf".


# NOMBRE:

# PEC5

Una vez importados los datos, con la misma base de datos y suponiendo que los datos corresponden a una muestra, responded a las siguientes cuestiones, indicando **tanto las instrucciones de R como los resultados numéricos obtenidos y los correspondientes comentarios**.

## Pregunta-1 (40%)

a) (20%) Queremos saber si podemos considerar que el valor medio de la variable "total_sales" en el conjunto total de videojuegos es igual a $0.75$ millones de copias o es inferior. Haced el contraste de hipótesis adecuado con un nivel de significación del $3\%$, usando únicamente las instrucciones de R que hacen directamente este contraste de hipótesis.



b) (20%) Ahora haced el mismo contraste de hipótesis mediante las fórmulas de los módulos, indicando:
   1) Las hipótesis nula y alternativa
   2) El estadístico de contraste.
   3) El p-valor
   4) Vuestra decisión y conclusión aplicadas a este caso considerado.

### Solución:
 
## Pregunta-2 (20%)

Contrastad con un nivel de significación del $5\%$ si la media de las puntuaciones del "critic_score" es la misma para la "PS4" que para la "XOne". Indicad qué tipo de contraste tenemos que hacer y las hipótesis nula y alternativa. Usad la instrucción de R que hace este tipo de contraste y, a partir de la salida de R, indicad el p-valor y la conclusión a que llegáis. Supondremos que las varianzas poblacionales son iguales.

### Solución:

## Pregunta-3 (20%)
Contrastad con un nivel de significación del $5\%$ si la proporción de videojuegos del género "Fighting" es igual al $7\%$. Indicad qué tipo de contraste tenemos que hacer y las hipótesis nula y alternativa. Usad la instrucción de R que hace este tipo de contraste y, a partir de la salida de R, indicad el p-valor y la conclusión a la que llegáis.

### Solución:


## Pregunta-4 (20%)
Queremos saber, con un nivel de significación del $5\%$, si la proporción de videojuegos del género "Role-Playing" disponibles para la consola "PS2" es superior a la proporción del mismo género para la consola "PS3". Indicad qué tipo de contraste tenemos que hacer y las hipótesis nula y alternativa. Usad la instrucción de R que hace este tipo de contraste y a partir de la salida de R, indicad el p-valor y la conclusión a la que llegáis.

### Solución:
